#[derive(PartialEq)]
pub enum DesktopEnvironment {
    Gnome,
    KDE,
}

pub struct Package {
    pub display: &'static str,
    pub key: &'static str,
    pub category: &'static str,
    pub desktop_environment: Option<DesktopEnvironment>,
}

pub fn get_all_packages() -> Vec<Package> {
    Vec::from([
        Package {
            display: "0 A.D.",
            key: "0ad",
            category: "Games",
            desktop_environment: None,
        },
        Package {
            display: "Ark Archiving",
            key: "ark",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Blender",
            key: "blender",
            category: "Multi Media",
            desktop_environment: None,
        },
        Package {
            display: "Cheese - Webcam",
            key: "cheese",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Chromium",
            key: "chromium",
            category: "Browsers",
            desktop_environment: None,
        },
        Package {
            display: "Cockpit - Web Interface",
            key: "cockpit",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "cups - Printer Support",
            key: "cups",
            category: "Desktop",
            desktop_environment: None,
        },
        Package {
            display: "cURL - Client URL",
            key: "curl",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "dconf Editor",
            key: "dconf-editor",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Deja Dup - Backups",
            key: "deja-dup",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Discord",
            key: "discord",
            category: "Communication",
            desktop_environment: None,
        },
        Package {
            display: "dotnet - C# runtime 8.0 LTS",
            key: "dotnet-runtime-8",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "dotnet - C# SDK 8.0 LTS",
            key: "dotnet-sdk-8",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Elisa Music Player",
            key: "elisa",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Epiphany - Gnome Web",
            key: "epiphany",
            category: "Browsers",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Evince - Document Viewer",
            key: "evince",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Eye of Gnome - Image Viewer",
            key: "eog",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Fedora Media Writer",
            key: "mediawriter",
            category: "Utilities",
            desktop_environment: None,
        },
        Package {
            display: "ffmpeg - Media Codecs",
            key: "ffmpeg",
            category: "Desktop",
            desktop_environment: None,
        },
        Package {
            display: "FileLight Disk Usage",
            key: "filelight",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Firefox",
            key: "firefox",
            category: "Browsers",
            desktop_environment: None,
        },
        Package {
            display: "Firefox ESR",
            key: "firefox-esr",
            category: "Browsers",
            desktop_environment: None,
        },
        Package {
            display: "Flutter",
            key: "flutter",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "gedit",
            key: "gedit",
            category: "Editors",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "GIMP",
            key: "gimp",
            category: "Multi Media",
            desktop_environment: None,
        },
        Package {
            display: "git - Version Control",
            key: "git",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Go Language",
            key: "golang",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "GParted",
            key: "gparted",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome 2048",
            key: "gnome-2048",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Boxes - VM Manager",
            key: "gnome-boxes",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Builder",
            key: "gnome-builder",
            category: "Editors",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Calculator",
            key: "gnome-calculator",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Calendar",
            key: "gnome-calendar",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Chess",
            key: "gnome-chess",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Clocks",
            key: "gnome-clocks",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Connections",
            key: "gnome-connections",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Contacts",
            key: "gnome-contacts",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Disk Usage",
            key: "baobab",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Disk Utility",
            key: "gnome-disk-utility",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Image Viewer",
            key: "loupe",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Maps",
            key: "gnome-maps",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Mines",
            key: "gnome-mines",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Music",
            key: "gnome-music",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Password Safe",
            key: "gnome-passwordsafe",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Photos",
            key: "gnome-photos",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Shell Extension",
            key: "gnome-shell-extensions",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Shell Extension Manager",
            key: "gnome-shell-extension-manager",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Software",
            key: "gnome-software",
            category: "Software",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Solitaire",
            key: "aisleriot",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Sound Recorder",
            key: "gnome-sound-recorder",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Sudoku",
            key: "gnome-sudoku",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome System Monitor",
            key: "gnome-system-monitor",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Tetris",
            key: "quadrapassel",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Text Editor",
            key: "gnome-text-editor",
            category: "Editors",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Tweaks",
            key: "gnome-tweaks",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Gnome Weather",
            key: "gnome-weather",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "GNU Cash - Accounting",
            key: "gnucash",
            category: "Applications",
            desktop_environment: None,
        },
        Package {
            display: "Gwenview - Image Viewer",
            key: "gwenview",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "htop - Process Reviewer",
            key: "htop",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "IceCat - GNU Browser",
            key: "icecat",
            category: "Browsers",
            desktop_environment: None,
        },
        Package {
            display: "imagemagick",
            key: "imagemagick",
            category: "Desktop",
            desktop_environment: None,
        },
        Package {
            display: "Intellij",
            key: "intellij",
            category: "Editors",
            desktop_environment: None,
        },
        Package {
            display: "Kate",
            key: "kate",
            category: "Editors",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KCalc - Calculator",
            key: "kcalc",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KDE Chess",
            key: "knights",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KDE Mines",
            key: "kmines",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KDE Sudoku",
            key: "ksudoku",
            category: "Games",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KdenLive Video Editor",
            key: "kdenlive",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KDevelop",
            key: "kdevelop",
            category: "Editors",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Kile - LaTex Editor",
            key: "kile",
            category: "Editors",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KSysGuard",
            key: "ksysguard",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "KWrite",
            key: "kwrite",
            category: "Editors",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "LaTex - Compiler",
            key: "latex",
            category: "Desktop",
            desktop_environment: None,
        },
        Package {
            display: "LibreOffice",
            key: "libreoffice",
            category: "Editors",
            desktop_environment: None,
        },
        Package {
            display: "MariaDB - Database",
            key: "mariadb",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "MP3 Metadata Editor",
            key: "id3v2",
            category: "Desktop",
            desktop_environment: None,
        },
        Package {
            display: "neovim - Text Editor",
            key: "neovim",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "nano - Text Editor",
            key: "nano",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Node.js - JavaScript RE",
            key: "node",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Okular - Document Viewer",
            key: "okular",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Plasma Discover",
            key: "plasma-discover",
            category: "Software",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Plasma System Monitor",
            key: "plasma-systemmonitor",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Podman - Containers",
            key: "podman",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Pycharm",
            key: "pycharm",
            category: "Editors",
            desktop_environment: None,
        },
        Package {
            display: "qtile - Window Manager",
            key: "qtile",
            category: "Desktop",
            desktop_environment: None,
        },
        Package {
            display: "RhythmBox",
            key: "rhythmbox",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Rust Language",
            key: "rust",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Shotwell",
            key: "shotwell",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Simple Scan",
            key: "simple-scan",
            category: "Utilities",
            desktop_environment: None,
        },
        Package {
            display: "Snap",
            key: "snapd",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Snap Store",
            key: "snap-store",
            category: "Software",
            desktop_environment: None,
        },
        Package {
            display: "Spectacle Screenshot",
            key: "spectacle",
            category: "Utilities",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "SSH - Secure Shell Protocol",
            key: "ssh",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Steam",
            key: "steam",
            category: "Games",
            desktop_environment: None,
        },
        Package {
            display: "Super Tux Kart",
            key: "supertuxkart",
            category: "Games",
            desktop_environment: None,
        },
        Package {
            display: "Thunderbird",
            key: "thunderbird",
            category: "Communication",
            desktop_environment: None,
        },
        Package {
            display: "TOR - The Onion Router",
            key: "torbrowser-launcher",
            category: "Browsers",
            desktop_environment: None,
        },
        Package {
            display: "Totem Video Player",
            key: "totem",
            category: "Multi Media",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Transmission (GTK) - Torrent",
            key: "transmission-gtk",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::Gnome),
        },
        Package {
            display: "Transmission (QT) - Torrent",
            key: "transmission-qt",
            category: "Applications",
            desktop_environment: Some(DesktopEnvironment::KDE),
        },
        Package {
            display: "Vietnamese Keyboard",
            key: "ibus-unikey",
            category: "Desktop",
            desktop_environment: None,
        },
        Package {
            display: "vim - Text Editor",
            key: "vim",
            category: "Server",
            desktop_environment: None,
        },
        Package {
            display: "Virt Manager",
            key: "virt-manager",
            category: "Applications",
            desktop_environment: None,
        },
        Package {
            display: "VLC",
            key: "vlc",
            category: "Multi Media",
            desktop_environment: None,
        },
        Package {
            display: "VS Code",
            key: "code",
            category: "Editors",
            desktop_environment: None,
        },
        Package {
            display: "Xonotic",
            key: "xonotic",
            category: "Games",
            desktop_environment: None,
        },
        Package {
            display: "yt-dlp - Download YouTube",
            key: "yt-dlp",
            category: "Desktop",
            desktop_environment: None,
        },
    ])
}
