[package]
name = "linux_setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.2"
rust-cli = { git = "https://github.com/GrantFBarnes/rust-cli", version = "0.1.0" }
